### ISSUE TITLE
Bug: Nordea 1100...1199 is type 1

### ISSUE THREAD

**Issue by cjnqt** [jelveby/bankverify#1]
Nordea accounts [1100...1199] should be type 1, not type 2, according to https://www.bankgirot.se/globalassets/dokument/anvandarmanualer/bankernaskontonummeruppbyggnad_anvandarmanual_sv.pdf

**Comment by jelveby** [comment]
Nicely spotted. 👍

I haven't worked actively on this for a while, so if you find any more issue, feel free to make a pull request. 😎
